Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 979, in on_activated_async
    run_view_callbacks('on_activated_async', view_id)
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 747, in run_view_callbacks
    callback(*args)
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 202, in exception_handler
    return event_handler(*args)
  File "/home/ram/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 363, in on_activated_async
    if self.view.is_loading() or not is_regular_view(self.view):
  File "/home/ram/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 78, in is_regular_view
    sheet = v.sheet()
  File "/opt/sublime_text/Lib/python38/sublime.py", line 2599, in sheet
    return make_sheet(self.sheet_id())
  File "/opt/sublime_text/Lib/python38/sublime.py", line 2352, in make_sheet
    if (sheet_id & 3) == 0:
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/ram/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 1014, in clear_async
  File "/home/ram/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/session_view.py", line 87, in on_before_remove
  File "/home/ram/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/code_lens.py", line 132, in clear_view
  File "/opt/sublime_text/Lib/python38/sublime.py", line 3909, in update
    for phantom, region in zip(self.phantoms, regions):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 987, in on_deactivated_async
    run_view_callbacks('on_deactivated_async', view_id)
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 202, in exception_handler
    return event_handler(*args)
  File "/opt/sublime_text/Packages/Default.sublime-package/save_on_focus_lost.py", line 8, in on_deactivated_async
    fname = view.file_name()
  File "/opt/sublime_text/Lib/python38/sublime.py", line 2667, in file_name
    if len(name) == 0:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/ram/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 1014, in clear_async
  File "/home/ram/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/session_view.py", line 87, in on_before_remove
  File "/home/ram/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/code_lens.py", line 132, in clear_view
  File "/opt/sublime_text/Lib/python38/sublime.py", line 3909, in update
    for phantom, region in zip(self.phantoms, regions):
TypeError: 'NoneType' object is not iterable
